version: "3"

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5442:5432'
    volumes:
      - ~/apps/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:7.0.1-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 8wfef78EWFhcw223223lsshWEwhwr2 --maxmemory 10mb
  keycloak:
    image: quay.io/keycloak/keycloak:latest
#    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
#      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
#    volumes:
#      - ~/server.crt.pem:/opt/keycloak/conf/server.crt.pem
#      - ~/server.key.pem:/opt/keycloak/conf/server.key.pem
    ports:
      - '8900:8080'
    command:
      - start-dev
      - --verbose
  discovery:
    build: ./service_discovery
    ports:
      - '9999:9999'
  gateway:
    build: ./api_gateway
    environment:
      EUREKA_SERVER: discovery
    depends_on:
      - discovery
    ports:
      - '9000:9000'
  blog-service:
      build: ./blog_project
      environment:
        EUREKA_SERVER: discovery
        KEYCLOAK_SERVER: keycloak
        POSTGRES_SERVER: postgres
        REDIS_SERVER: redis
      depends_on:
        - discovery
        - keycloak
        - postgres
        - redis
  user-service:
    build: ./user_service
    environment:
      EUREKA_SERVER: discovery
      KEYCLOAK_SERVER: keycloak
      REDIS_SERVER: redis
    depends_on:
      - discovery
      - keycloak
      - redis
