admin:
  password: admin
  username: admin
keycloak:
  token:
    endpoint: /realms/master/protocol/openid-connect/token
  url: http://${KEYCLOAK_SERVER:localhost}:8900
  users:
    get: /admin/realms/myrealm/users
server:
  port: 0
spring:
  application:
    name: user-service
  data:
    redis:
      #      url: redis://:8wfef78EWFhcw223223lsshWEwhwr2@${REDIS_SERVER:localhost}:6379
      host: ${REDIS_SERVER:localhost}
      port: 6379
      password: 8wfef78EWFhcw223223lsshWEwhwr2
      database: 0


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instanceId: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:9999/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5